# Generated by Django 5.1.3 on 2025-05-18 10:52

import dashboard.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppartmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="appartment_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommercialImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="commercial_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reviews", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "customer_images",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="plot_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff_UserAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("THMID", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "referral_code",
                    dashboard.models.AlphaNumericFieldfive(
                        blank=True, max_length=5, null=True, unique=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Appartment",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                ("bhk", models.CharField(blank=True, max_length=10, null=True)),
                ("bathrooms", models.CharField(blank=True, max_length=10, null=True)),
                ("parking", models.CharField(blank=True, max_length=10, null=True)),
                ("floor_no", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "total_floors",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("maintenance", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "furnishing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Furnished", "Furnished"),
                            ("Semi-Furnished", "Semi-Furnished"),
                            ("UnFurnished", "UnFurnished"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "land_area_sqft",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "carpet_area_sqft",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("sqft_price", models.CharField(blank=True, max_length=10, null=True)),
                ("total_price", models.CharField(blank=True, max_length=10, null=True)),
                ("area", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "nearby_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nearby_busortrain",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "facing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("East", "East"),
                            ("West", "West"),
                            ("North", "North"),
                            ("South", "South"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "listed_by",
                    models.CharField(
                        blank=True,
                        choices=[("Builder", "Builder"), ("Dealer", "Dealer")],
                        default="Builder",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[("New", "New"), ("ReSale", "ReSale")],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "appartment_type",
                    models.CharField(
                        blank=True,
                        choices=[("Appartment", "Appartment"), ("Villa", "Villa")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("avaliable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appartment_images",
                        to="dashboard.appartmentimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commercial",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "furnishing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Furnished", "Furnished"),
                            ("Semi-Furnished", "Semi-Furnished"),
                            ("UnFurnished", "UnFurnished"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "listed_by",
                    models.CharField(
                        blank=True,
                        choices=[("Builder", "Builder"), ("Dealer", "Dealer")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "super_area_sqft",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "carpet_area_sqft",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("sqft_price", models.CharField(blank=True, max_length=10, null=True)),
                ("total_price", models.CharField(blank=True, max_length=10, null=True)),
                ("maintenance", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "facing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("East", "East"),
                            ("West", "West"),
                            ("North", "North"),
                            ("South", "South"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("parking", models.CharField(blank=True, max_length=10, null=True)),
                ("washrooms", models.CharField(blank=True, max_length=10, null=True)),
                ("area", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "nearby_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nearby_busortrain",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("avaliable", models.BooleanField(default=True)),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[("New", "New"), ("ReSale", "ReSale")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="commercial_images",
                        to="dashboard.commercialimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                ("sqft", models.CharField(blank=True, max_length=10, null=True)),
                ("total_sqft", models.CharField(blank=True, max_length=10, null=True)),
                ("total_price", models.CharField(blank=True, max_length=10, null=True)),
                ("area", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "nearby_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nearby_busortrain",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("length", models.CharField(blank=True, max_length=100, null=True)),
                ("breadth", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "facing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("East", "East"),
                            ("West", "West"),
                            ("North", "North"),
                            ("South", "South"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "listed_by",
                    models.CharField(
                        choices=[("Builder", "Builder"), ("Dealer", "Dealer")],
                        default="Builder",
                        max_length=30,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[("New", "New"), ("ReSale", "ReSale")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("avaliable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True, related_name="plot_images", to="dashboard.plotimage"
                    ),
                ),
            ],
        ),
    ]
