# Generated by Django 5.1.3 on 2024-11-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('college', 'College'), ('school', 'School'), ('hospital', 'Hospital'), ('industry', 'Industry'), ('eatout', 'Eat Out'), ('gov_office', 'Government Office')], max_length=50)),
                ('address', models.TextField()),
                ('distance_from_property', models.FloatField(help_text='Distance in kilometers')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('commercial', 'Commercial Property'), ('acres', 'Acres/Cents'), ('villa', 'Individual Villa'), ('resale_home', 'Resale Home'), ('resale_apartment', 'Resale Apartment'), ('new_apartment', 'New Apartment'), ('ongoing_project', 'Ongoing Project'), ('upcoming_project', 'Upcoming Project'), ('completed_project', 'Completed Project'), ('construction_project', 'Construction Project')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.FloatField(help_text='Area in square feet or acres')),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('nearby_amenities', models.ManyToManyField(blank=True, related_name='properties', to='home.amenity')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='property_documents/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.property')),
            ],
        ),
    ]
